name = "MultiWriters"
uuid = "7b4705cc-05b2-48bd-b53f-c512a570c58d"
authors = ["goropikari <goropikari56@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
